name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH  # Make Bun available globally
        shell: bash

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages  # the branch to deploy to
          folder: build     # the folder to deploy
          token: ${{ secrets.GITHUB_TOKEN }}
