name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This can be your default branch or another branch you're using

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
        shell: bash

      - name: Set up Bun
        run: export PATH="$HOME/.bun/bin:$PATH"

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages  # The branch to deploy to
          folder: build     # The folder to deploy (adjust based on your build output folder, typically it's `build` or `dist`)
          token: ${{ secrets.GITHUB_TOKEN }}
